name: jsapp-build
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:15.5.0-alpine3.10
    steps:
      - uses: actions/checkout@v3
      - name: Docker image build
        run: |
          npm install
#          docker build -t ghcr.io/$DOCKER_USER/jsapp:v1.0.0 .
#      - name: Docker login
#        run: |
#          docker login ghcr.io -u $DOCKER_USER -p $DOCKER_TOKEN
#      - name: Docker image push
#        run: |
#          docker push ghcr.io/$DOCKER_USER/jsapp:v1.0.0
