name: jsapp-build

# Controls when the workflow will run
on:
  push:
    branches: 
    - master
#    - feature-*
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: ASzc/change-string-case-action@v2
        id: tag
        with:
          string: ${{ github.ref }}
      - name: Docker image build
        run: |
          TAG=${{ steps.tag.outputs.lowercase }}
          echo docker build -t ghcr.io/$DOCKER_USER/jsapp:${TAG##*/} .
          echo docker login ghcr.io -u $DOCKER_USER -p $DOCKER_TOKEN
          echo docker push ghcr.io/$DOCKER_USER/jsapp:${TAG##*/}

