# This is a basic workflow to help you get started with Actions

name: jsapp-build

# Controls when the workflow will run
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  env:
    DOCKER_USER: ${{ secrets.DOCKER_USER }}
    DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        run: |
          docker login ghcr.io -u $DOCKER_USER -p $DOCKER_TOKEN
#      - name: Docker build
#        run: |
#          docker build -t $DOCKER_USER/jsapp:v1.0.0 .
#      - name: Docker push
#        run: |
#          docker push ghcr.io/$DOCKER_USER/jsapp:v1.0.0
