name: jsapp-build

# Controls when the workflow will run
on:
  push:
    branches: 
#    - master
    - feature-*
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Docker image build
        run: |
          docker build -t ghcr.io/$DOCKER_USER/jsapp:v1.0.0 .
      - name: Docker login
        run: |
          docker login ghcr.io -u $DOCKER_USER -p $DOCKER_TOKEN
      - name: Docker image push
        run: |
          docker push ghcr.io/$DOCKER_USER/jsapp:${GITHUB_REF##*/}

