name: jsapp-build

# Controls when the workflow will run
on:
  push:
    branches: 
    - master
    - FS-*
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: "ghcr.io"
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: tj-actions/branch-names@v6
        id: branch
      - uses: xom9ikk/split@v1
        id: repo
        with:
          string: ${{ github.repository }}
          separator: /
          limit: -1
      - uses: ASzc/change-string-case-action@v2
        id: tag
        with:
          string: ${{ steps.branch.outputs.current_branch }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Artifactory
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_TOKEN }}
      - name: Check branch 2
        if: github.ref_name == 'master'
        run: echo Branch ${{ github.ref_name }}
     # - name: Build and push
     #   uses: docker/build-push-action@v3
     #   with:
     #     context: .
     #     tags: ${{ env.DOCKER_REGISTRY }}/jsapp:${{ steps.tag.outputs.lowercase }}
     #     push: true
      - name: Docker image build and additional output
        run: |
          echo GITHUB_REPOSITORY ${GITHUB_REPOSITORY#*/}
          echo github.ref ${{ github.ref }}
          echo GITHUB_REF_NAME ${GITHUB_REF_NAME}
          echo github.repository ${{ github.repository }}
          echo steps.tag.outputs.lowercase ${{ steps.tag.outputs.lowercase }}
          echo repo ${{ steps.repo.outputs._1 }}
     
          #TAG=${{ steps.tag.outputs.lowercase }}
          #docker build -t ghcr.io/$DOCKER_USER/jsapp:${TAG##*/} .
          #docker login ghcr.io -u $DOCKER_USER -p $DOCKER_TOKEN
          #docker push ghcr.io/$DOCKER_USER/jsapp:${TAG##*/}

