name: jsapp-build
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine3.15
    steps:
      - name: Node version 16 in jobs config
        run: node -v
      - name: Node version 13.5.0
        uses: docker://node:13.5.0-alpine3.10
        with:
          entrypoint: /usr/local/bin/node
          args: -v
      - name: Node version 15.5.0
        uses: docker://node:15.5.0-alpine3.10
        with:
          entrypoint: /usr/local/bin/node
          args: -v

