name: jsapp-build

# Controls when the workflow will run
on:
  push:
    branches: 
    - master
#    - feature-*
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: ASzc/change-string-case-action@v2
        id: lowercase
        with:
          string: ${{ github.ref }}
      - name: Docker image build
        run: |
          echo "The replaced value is ${{ steps.lowercase.outputs.lowercase }}"
          TAG=${{ steps.lowercase.outputs.lowercase }}
          echo docker build -t ghcr.io/$DOCKER_USER/jsapp:${TAG} .
#      - name: Docker login
#        run: |
#          echo docker login ghcr.io -u $DOCKER_USER -p $DOCKER_TOKEN
#      - name: Docker image push
#        run: |
#          echo docker push ghcr.io/$DOCKER_USER/jsapp:${BRANCH}

