name: jsapp-build

# Controls when the workflow will run
on:
  push:
    branches: 
    - master
#    - feature-*
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      BRANCH: $(echo ${GITHUB_REF##*/} | tr '[:upper:]' '[:lower:]')
    steps:
      - uses: actions/checkout@v3
      - name: Docker image build
        run: |
          echo docker build -t ghcr.io/$DOCKER_USER/jsapp:${BRANCH} .
      - name: Docker login
        run: |
          echo docker login ghcr.io -u $DOCKER_USER -p $DOCKER_TOKEN
      - name: Docker image push
        run: |
          echo docker push ghcr.io/$DOCKER_USER/jsapp:${BRANCH}

